version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_storage:/data

  minio_create_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo Root User: ${MINIO_ROOT_USER};
      echo Root Password: ${MINIO_ROOT_PASSWORD};
      echo Default Bucket: ${MINIO_DEFAULT_BUCKET};
      sleep 5;
      /usr/bin/mc alias set dev_minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing dev_minio/${MINIO_DEFAULT_BUCKET};
      /usr/bin/mc policy set public dev_minio/${MINIO_DEFAULT_BUCKET};
      exit 0;
      "
    env_file:
      - .env
volumes:
  minio_storage:
